### ISSUE TITLE
BUG with distinct in IfxGrammar.php

### ISSUE THREAD

**Issue by jsamaniegog** [isoc-il/laravel-ifx#1]
First of all, thanks for this post https://blog.rabin.io/sysadmin/laravel-lumen-informix, it has helped me a lot.

For more convenience, it would be nice if you published the repository in packagist.

On the other hand I wanted to tell you that there is a bug in the original source [https://github.com/llaiajiale/laravel-ifxrtada](https://github.com/llaiajiale/laravel-ifx), but he does not update the repository. I tell you in case you could fix it, otherwise I'll fix it myself.

In IfxGrammar.php there is a syntax error with the distinct, it should be like this:

```
        $select = 'select';

         if ($ query-> offset> 0) {
             $ select. = 'skip'. (int) $ query-> offset;
         }

         if ($ query-> limit> 0) {
             $ select. = 'first'. (int) $ query-> limit;
         }

         $ select. = $ query-> distinct? 'distinct': '';
```
The "distinct" must be after "first".

Regards, Javier.

**Comment by rabin-io** [comment]
Hi @jsamaniegog, 

I was not able to reproduce it, 


```
>>> DB::table('users')->select('status')->distinct()->get()
=> Illuminate\Support\Collection {#2960
     all: [
       {#2963
         +"status": "1",
       },
       {#2964
         +"status": "4",
       },
     ],
   }
```

Can you provide an example to reproduce this problem ?

**Comment by jsamaniegog** [comment]
Try with eloquent:

User::distinct()->paginate();

**Comment by rabin-io** [comment]
OK, just pushed a fix to my repo, and also submitted a PR to the upstream repo.

**Comment by jsamaniegog** [comment]
Perfect!, thank you very much.
