### ISSUE TITLE
CONNECTION LARAVEL 7

### ISSUE THREAD

**Issue by rockdrc** [isoc-il/laravel-ifx#3]
Hello!

Is there any doc, to install with the version of "laravel/framework": "^7.29" ?

Thanks in advance

**Comment by rabin-io** [comment]
There is a blog post about it here : https://blog.rabin.io/sysadmin/laravel-lumen-informix

just add the repo section to your composer file, 

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/isoc-il/laravel-ifx"
        }
    ],
```

![image](https://user-images.githubusercontent.com/5116363/150022499-f48b4907-25e5-4060-a90a-7e6c4688db1b.png)


and run 

    composer require isoc-il/laravel-ifx:dev-master
