### ISSUE TITLE
Laravel 9 Connection

### ISSUE THREAD

**Issue by JustyrTsaiLar** [isoc-il/laravel-ifx#7]
https://blog.rabin.io/sysadmin/laravel-lumen-informix
i follow this to go

setup .ENV  & connections both 
and with artisan tinker command DB::select( ' . . . . .  ')  
but still get  PDOException with message 'could not find driver'  

any ideal ?  

thank you all , you save my day

**Comment by rabin-io** [comment]
You need to install the PHP PDO driver for informix, the driver it self can be downloaded from PECL - https://pecl.php.net/package/pdo_informix. But it require the Informix Client SDK to compile them, which you need to download from IBM site.
